language: ruby
sudo: false

cache:
  bundler: true

services:
  - memcached

bundler_args: --without test --jobs 3 --retry 3
before_install:
  - gem install bundler -v=1.11.2

before_script:
  - bundle update

script: 'ci/travis.rb'

env:
  matrix:
    - "GEM=ar:mysql2"

rvm:
  - 2.3.3
  - 2.4.5
