language: ruby
sudo: false

cache:
  bundler: true

services:
  - memcached

bundler_args: --without test --jobs 3 --retry 3
before_install:
  - gem install bundler -v=1.11.2

before_script:
  - bundle update

script: 'ci/travis.rb'

env:
  matrix:
    - "GEM=railties"
    - "GEM=ap,am,amo,ares,as"
    - "GEM=ar:mysql"
    - "GEM=ar:mysql2"
    - "GEM=ar:sqlite3"
    - "GEM=ar:postgresql"

rvm:
  - 2.3.3
  - 2.4.5
